RESET role;

CREATE SCHEMA customerexample
 AUTHORIZATION api_owner;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customerexample REVOKE EXECUTE ON FUNCTIONS FROM public;
ALTER DEFAULT PRIVILEGES FOR ROLE api_owner IN SCHEMA customerexample REVOKE EXECUTE ON FUNCTIONS FROM public;
ALTER DEFAULT PRIVILEGES IN SCHEMA ztest_shard2 REVOKE EXECUTE ON FUNCTIONS FROM public;

ALTER DEFAULT PRIVILEGES FOR ROLE api_owner IN SCHEMA customerexample GRANT EXECUTE ON FUNCTIONS TO api_executor;

GRANT USAGE ON SCHEMA customerexample TO api_usage;

SET ROLE TO api_owner;

SET search_path TO customerexample, public;
