RESET role;

CREATE SCHEMA ztest_shard1
 AUTHORIZATION api_owner;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ztest_shard1 REVOKE EXECUTE ON FUNCTIONS FROM public;
ALTER DEFAULT PRIVILEGES FOR ROLE api_owner IN SCHEMA ztest_shard1 REVOKE EXECUTE ON FUNCTIONS FROM public;
ALTER DEFAULT PRIVILEGES IN SCHEMA ztest_shard1 REVOKE EXECUTE ON FUNCTIONS FROM public;

ALTER DEFAULT PRIVILEGES FOR ROLE api_owner IN SCHEMA ztest_shard1 GRANT EXECUTE ON FUNCTIONS TO api_executor;

GRANT USAGE ON SCHEMA ztest_shard1 TO api_usage;

SET ROLE TO api_owner;

SET search_path TO ztest_shard1, public;
